export enum Roles {
  ROLE_SUPER_ADMIN = 'ROLE_SUPER_ADMIN',
  ROLE_ADMIN = 'ROLE_ADMIN',
  ROLE_FEEDBACK = 'ROLE_FEEDBACK',
  ROLE_REFERRALS = 'ROLE_REFERRALS',
  ROLE_WORK_PLAN = 'ROLE_WORK_PLAN'
}

