export enum Roles {
  ROLE_SUPER_ADMIN = 'ROLE_SUPER_ADMIN',
  ROLE_ADMIN = 'ROLE_ADMIN',
  ROLE_MEAL = 'ROLE_MEAL',
  ROLE_FINANCE = 'ROLE_FINANCE',
  ROLE_ED = 'ROLE_ED',
  ROLE_DATA_COLLECTOR = 'ROLE_DATA_COLLECTOR',
  ROLE_APPLICANT = 'ROLE_APPLICANT',
  ROLE_PROGRAM_OFFICER = 'ROLE_PROGRAM_OFFICER',
  ROLE_STAFF_DATA_MANAGER = 'ROLE_STAFF_DATA_MANAGER',
  ROLE_STAFF_DATA_VIEWER = 'ROLE_STAFF_DATA_VIEWER',
  ROLE_PARTNER_DATA_VIEWER = 'ROLE_PARTNER_DATA_VIEWER',
  ROLE_PARTNER_DATA_MANAGER = 'ROLE_PARTNER_DATA_MANAGER',
}
