export enum Roles {
  ROLE_SUPER_ADMIN = 'ROLE_SUPER_ADMIN',
  ROLE_ADMIN = 'ROLE_ADMIN',
  BUDGET_HOLDER = 'BUDGET_HOLDER',
  ROLE_REBUILD_DATA_VIEWER = 'ROLE_REBUILD_DATA_VIEWER',
  ROLE_REBUILD_DATA_MANAGER = 'ROLE_REBUILD_DATA_MANAGER',
  ROLE_DATA_COLLECTOR = 'ROLE_DATA_COLLECTOR',
}

