image: node:12

variables:
  SERVER_HOST: "157.230.227.3"
  WEBAPP_FOLDER: "/var/www/kengamis/"
  RUNNABLE_JARS_FOLDER: "/opt/runnable-jars/kengamis-server/"

before_script:
  - apt-get update -qq && apt-get install -y -qq unzip
  - apt-get install zip
  - apt-get install sshpass
  - cd client
  - npm install
  - npm install -g @angular/cli

deploy:
  artifacts:
    paths:
      - dist/
  stage: deploy
  only:
    - crvpf
  script:
    - cd ..
    - gradlew clean
    - gradlew build -x test -x integrationTest
    - sshpass -p $USER_PASS scp server/build/libs/crvpf-server.jar root@$SERVER_HOST:$RUNNABLE_JARS_FOLDER
    - sshpass -p $USER_PASS ssh root@$SERVER_HOST "cd $RUNNABLE_JARS_FOLDER && ./start-kengamis.sh"
    - echo "Done Deploying crvpf server :)"
    - cd client
    - ng build --prod --base-href kengamis
    - cd dist/kengamis/
    - sshpass -V
    - export SSHPASS=$USER_PASS
    - echo "Copying to server..."
    - sshpass -e scp -o stricthostkeychecking=no -r * root@$SERVER_HOST:$WEBAPP_FOLDER
    - echo "Done Deploying crvpf client :)"